/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hasan' at '04.03.17 10:56' with Gradle 3.1
 *
 * @author Hasan, @date 04.03.17 10:56
 */
class Library {
    boolean someLibraryMethod() {
        return true;
    }
}
